include:
  - core-identity/cloudflared/docker-compose.yml
  - core-identity/keycloak/docker-compose.yml
  - management/portainer/docker-compose.yml

networks:
  sovereign_net:
    driver: bridge
    name: sovereign_net