include:
  - 2-applications/identity/docker-compose.yml
  - 2-applications/secrets/docker-compose.yml
  - 2-applications/automation/docker-compose.yml
  - 2-applications/security/docker-compose.yml
  - 2-applications/observability/docker-compose.yml

networks:
  sovereign_net:
    external: true
