services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-server
    command: start # Production mode enabled!
    restart: unless-stopped
    env_file: .env # Ansible injects the DO Database & Vault Secrets here
    volumes:
      - ./providers/keycloak-webhook-provider-core.jar:/opt/keycloak/providers/keycloak-webhook-provider-core.jar
      - ./providers/keycloak-webhook-provider-http.jar:/opt/keycloak/providers/keycloak-webhook-provider-http.jar
    environment:
      # Your custom proxy and proxy routing settings
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
      KC_HOSTNAME_ADMIN: https://keycloak-admin.charif-labs.tech
      
      # Your N8N Webhook Triggers
      WEBHOOK_HTTP_BASE_PATH: "http://sovereign-stack-n8n-1:5678/webhook/jml-trigger"
      WEBHOOK_HTTP_HEADERS: '{"X-Keycloak-Token": "SECURE_SECRET_Keycloak-2026"}'
      
    networks:
      - sovereign_net

networks:
  sovereign_net:
    external: true