---
- name: Ensure python interpreter is available
  hosts: docker_hosts
  become: true
  gather_facts: false
  tasks:
    - name: Install python3
      ansible.builtin.raw: test -e /usr/bin/python3 || (apt update && apt install -y python3)
      changed_when: false
      run_once: true  # noqa run-once[task]
      delegate_to: "{{ inventory_hostname }}"

- name: Provision Host
  import_playbook: provision_docker_host.yml

- name: Deploy Stacks
  import_playbook: deploy_docker_stacks.yml
