---
- name: Include SSH hardening tasks
  ansible.builtin.include_tasks:
    file: ssh.yml

- name: Check if Tailscale is connected
  ansible.builtin.command: tailscale status
  register: linux_hardening_ts_status
  changed_when: false
  failed_when: false

- name: Include Firewall configuration tasks
  ansible.builtin.include_tasks:
    file: firewall.yml
  when: "'100.' in ansible_host | default(inventory_hostname)"

- name: Include User management tasks
  ansible.builtin.include_tasks:
    file: users.yml
