---
- name: Ensure admin users exist and have correct groups and SSH keys
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | join(',') }}"
    append: true
    state: present
    shell: /bin/bash
    generate_ssh_key: false
  loop: "{{ admin_users | default([]) }}"

- name: Deploy SSH public keys for admin users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"
    state: present
  loop: "{{ admin_users | default([]) }}"
  when: item.ssh_key is defined and item.ssh_key | length > 0

- name: Ensure passwordless sudo for mgmt user
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/mgmt
    line: 'mgmt ALL=(ALL) NOPASSWD:ALL'
    create: yes
    validate: 'visudo -cf %s'
    mode: '0440'
