---
# ansible/roles/docker_applications/tasks/main.yml
- name: Ensure base Docker applications directory exists on remote host
  ansible.builtin.file:
    path: "{{ docker_root_path }}"
    state: directory
    mode: '0755'

- name: Copy Docker applications directory to remote host
  ansible.builtin.copy:
    src: ../../../docker/
    dest: "{{ docker_root_path }}/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Find all docker-compose.yml files in copied applications
  ansible.builtin.find:
    paths: "{{ docker_root_path }}"
    patterns: docker-compose.yml
    recurse: true
  register: docker_applications_compose_files

- name: Deploy Docker Compose stacks
  ansible.builtin.command: docker compose up -d --remove-orphans
  args:
    chdir: "{{ item.path | ansible.builtin.dirname }}"
  loop: "{{ docker_applications_compose_files.files }}"
  changed_when: false
