[all:vars]
ansible_python_interpreter=/usr/bin/python3

[primary_host]
105.159.248.207 ansible_user=mgmt

[standby_host]
100.107.233.53 ansible_user=mgmt

[docker_hosts:children]
primary_host
standby_host
