services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - sovereign_net

volumes:
  portainer_data:
    name: portainer_data

networks:
  sovereign_net:
    external: true # Network created by the Master file