services:
  vault:
    image: hashicorp/vault:latest
    container_name: core_vault
    user: "100:100"
    cap_add:
      - IPC_LOCK
    environment:
      SKIP_SETCAP: "true"
      SKIP_CHOWN: "true"
      VAULT_API_ADDR: "http://127.0.0.1:8200"
    ports:
      - "127.0.0.1:8200:8200" # Strict local binding to prevent external exposure
    volumes:
      - ./vault-data:/vault/file
      - ./vault.hcl:/vault/custom/vault.hcl
    command: server -config=/vault/custom/vault.hcl
    restart: unless-stopped
    networks:
      - sovereign_net

networks:
  sovereign_net:
    external: true
