name: Infrastructure CI

# This triggers the pipeline every time you push to the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-docker:
    name: Validate Docker Compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Create dummy .env for validation
        run: touch docker/.env
        
      - name: Validate Compose File Syntax
        run: docker compose -f docker/docker-compose.yml config -q

  validate-terraform:
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Terraform Init (Local Backend)
        run: terraform init -backend=false
        working-directory: ./terraform
        
      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform
